
default: &default
  adapter: mysql2
  host: localhost
  username: root
  password: ""
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: myrubyblog_dev

test:
  <<: *default
  database: myrubyblog_test

production:
  <<: *default
  database: myrubyblog_prod
